"""add_credit_cards_and_expense_credit_card_id

Revision ID: fe6a79b6a5e1
Revises: c4d8e2f1a3b5
Create Date: 2026-05-04 14:10:43.881863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6a79b6a5e1'
down_revision: Union[str, Sequence[str], None] = 'c4d8e2f1a3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('last_four', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('expenses', sa.Column('credit_card_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'credit_cards', ['credit_card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'credit_card_id')
    op.drop_table('credit_cards')
    # ### end Alembic commands ###
